var listStudents = [{
        username: "phitm",
        password: "Tranphi@2642",
        fullname: "Trần Mậu Phi",
        email: "phitmps16509@fpt.edu.vn",
        gender: "Nam",
        birthday: '26-04-2002',
        schoolfree: "35.000.000",
        mark: 8.5,
        img: "avt1.jpg",
    },
    {
        username: "thangnnc",
        password: "Thang@123",
        fullname: "Nguyễn Nhật Cao Thăng",
        email: "thangnncps14579@fpt.edu.vn",
        gender: "Nam",
        birthday: "12-03-2000",
        schoolfree: "35.000.000",
        mark: 10.0,
        img: "thang.jpg",
    },
    {
        username: "truongpnd",
        password: "Truong@123",
        fullname: "Phan Nguyễn Đăng Trường",
        email: "truongpndps16501@fpt.edu.vn",
        gender: "Nam",
        birthday: "08-08-2002",
        schoolfree: "35.000.000",
        mark: 5.0,
        img: "truong.jpg",
    },
    {
        username: "duydh",
        password: "Duy@123",
        fullname: "Đặng Hoàng Duy",
        email: "duydhps16493@fpt.edu.vn",
        gender: "Nam",
        birthday: "01-01-2002",
        schoolfree: "35.000.000",
        mark: 7.0,
        img: "duy.jpg",
    },
    {
        username: "nhavt",
        password: "Nha@123",
        fullname: "Võ Thanh Nhã",
        email: "nhavtps16500@fpt.edu.vn",
        gender: "Nam",
        birthday: "08-01-2002",
        schoolfree: "35.000.000",
        mark: 6.0,
        img: "nha.jpg",
    },
    {
        username: "tiennld",
        password: "Tien@123",
        fullname: "Nguyễn Lê Duy Tiến",
        email: "tiennldps16590@fpt.edu.vn",
        gender: "Nữ",
        birthday: "01-01-2002",
        schoolfree: "35.000.000",
        mark: 4.0,
        img: "tien.jpg",
    },
];