[{
        "Id": "ADAV",
        "Name": "Lập trình Android nâng cao",
        "Logo": "ADAV.jpg",
        "Teacher": "Nguyễn Ngọc Chấn",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "100",
        "Time": "1500",
        "Type": "Back-end"
    },
    {
        "Id": "ADBS",
        "Name": "Lập trình Android cơ bản",
        "Logo": "ADBS.jpg",
        "Teacher": "Trần Thị Hường",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "100",
        "Time": "1500",
        "Type": "Back-end"
    },
    {
        "Id": "ADUI",
        "Name": "Thiết kế giao diện trên Android",
        "Logo": "ADUI.jpg",
        "Teacher": "Trần Thị Hường",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "100",
        "Time": "1500",
        "Type": "Front-end"
    },
    {
        "Id": "ASNE",
        "Name": "Lập trình ASP.NET",
        "Logo": "ASNE.png",
        "Teacher": "Nguyễn Văn Long",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "100",
        "Time": "1500",
        "Type": "Back-end"
    },
    {
        "Id": "CLCO",
        "Name": "Điện toán đám mây",
        "Logo": "CLCO.jpg",
        "Teacher": "Lê Văn Phụng",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "100",
        "Time": "1500",
        "Type": "Back-end"
    },
    {
        "Id": "DBAV",
        "Name": "SQL Server",
        "Logo": "DBAV.png",
        "Teacher": "Thân Hoàng Lộc",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "500",
        "Time": "2100",
        "Type": "Order"
    },
    {
        "Id": "DBBS",
        "Name": "Cơ sở dữ liệu",
        "Logo": "DBBS.png",
        "Teacher": "Thân Hoàng Lộc",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "300",
        "Time": "1500",
        "Type": "Order"
    },
    {
        "Id": "GAME",
        "Name": "Lập trình game 2D",
        "Logo": "GAME.png",
        "Teacher": "Nguyễn Ngọc Chấn",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "17",
        "Time": "1500",
        "Type": "Back-end"
    },
    {
        "Id": "HTCS",
        "Name": "HTML5 và CSS3",
        "Logo": "HTCS.jpg",
        "Teacher": "Nguyễn Thị Thanh Xuân",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "23",
        "Time": "1500",
        "Type": "Front-end"
    },
    {
        "Id": "INMA",
        "Name": "Internet Marketing",
        "Logo": "INMA.jpg",
        "Teacher": "Nguyễn Hải Đăng",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "190",
        "Time": "1500",
        "Type": "Order"
    },
    {
        "Id": "JAAV",
        "Name": "Lập trình Java nâng cao",
        "Logo": "JAAV.png",
        "Teacher": "Cao Hoàng Phúc",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "70",
        "Time": "1500",
        "Type": "Back-end"
    },
    {
        "Id": "JABS",
        "Name": "Lập trình hướng đối tượng với Java",
        "Logo": "JABS.png",
        "Teacher": "Lê Văn Phụng",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "50",
        "Time": "1500",
        "Type": "Back-end"
    },
    {
        "Id": "JSPR",
        "Name": "Lập trình JavaScript",
        "Logo": "JSPR.png",
        "Teacher": "Nguyễn Thanh Điền",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "110",
        "Time": "1500",
        "Type": "Front-end"
    },
    {
        "Id": "LAYO",
        "Name": "Thiết kế layout",
        "Logo": "LAYO.jpg",
        "Teacher": "Trần Bá Hộ",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "100",
        "Time": "1500",
        "Type": "Front-end"
    },
    {
        "Id": "MOWE",
        "Name": "Thiết kế web cho điện thoại di động",
        "Logo": "MOWE.png",
        "Teacher": "Nguyễn Thị Thanh Xuân",
        "Images": "",
        "Date": "2022 - 04 - 03",
        "Views": "214",
        "Time": "900",
        "Type": "Front-end"
    },
    {
        "Id": "PHPP",
        "Name": "Lập trình PHP",
        "Logo": "PHPP.png",
        "Teacher": "Nguyễn Thị Thanh Xuân",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "1730",
        "Time": "900",
        "Type": "Front-end"
    },
    {
        "Id": "PMAG",
        "Name": "Quản lý dự án với Agile",
        "Logo": "PMAG.jpg",
        "Teacher": "Lại Minh Đăng",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "120",
        "Time": "900",
        "Type": "Order"
    },
    {
        "Id": "VBPR",
        "Name": "Lập trình VB.NET",
        "Logo": "VBPR.png",
        "Teacher": "Nguyễn Văn Long",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "100",
        "Time": "1500",
        "Type": "Back-end"
    },
    {
        "Id": "WEBU",
        "Name": "Xây dựng trang web",
        "Logo": "WEBU.jpg",
        "Teacher": "Phan Viết Thế",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "200",
        "Time": "900",
        "Type": "Front-end"
    },
    {
        "Id": "ADTE",
        "Name": "Kiểm thử và triển khai ứng dụng Android",
        "Logo": "ADTE.jpg",
        "Teacher": "Nguyễn Ngọc Chấn",
        "Des": "Đây là bài thi trắc nghiệm online dành cho tất cả các bạn sinh viên. Lưu ý tuyệt đối không được mở tab khác để tra cứu tài liệu. Bài thi phải đạt tối đa là 5 điểm thì mới được pass. Chúc các bạn sinh viên làm bài đạt kết quả tốt nhất.",
        "Date": "2022 - 04 - 03",
        "Views": "165",
        "Time": "900",
        "Type": "Order"
    }
]